### ISSUE TITLE
Master Branch

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/site-ffffm#18]
Brauchen wir noch den Master Branch hier? Ich denke das er eher Menschen verwirrt, als hilft.

**Comment by oszilloskop** [comment]
Hier wird er noch benötigt.
In der README.md ist zu lesen, wie er zu werten ist.

[..]
master:
Dummy Branch (wird nicht verwendet)
[..]

**Comment by oszilloskop** [comment]
Verwirrender sind evtl. eher folgende Branches:
 - DNS-Server 
 - Dev-DNS-Server
 - skorpy-2009-patch-1

n_babel-work ist ja noch in Diskussion mit Klaus_Dieter

**Comment by skorpy2009** [comment]
@oszilloskop ich finde "Dev-DNS-Server" nicht verwirrend, da ist für dich ein offener Pull Request. https://github.com/freifunk-ffm/site-ffffm/pull/16

**Comment by christf** [comment]
>n_babel-work ist ja noch in Diskussion mit Klaus_Dieter
Das ist ein ungünstig benannter Branch, der den babel-PR enthält. Sobald 
der gemerged ist, kann der weg. Diskussionserfordernis sah ich da 
bislang nicht, wenn es da was gibt, können wir uns aber gern mal zum 
Vorgehen zusammensetzen.

Vielleicht ist es auch sinnvoll, wenn wir die Branchnamen so 
standardisieren, dass dieser Reibungspunkt entfällt. 


Was brauchst Du, Jason, damit branches nicht verwirren?

Ich möchte gern wissen, wer der Ansprechpartner für einen Branch ist, 
wer ihn erzeugt hat. Daher finde ich die Nennung des usernamens im 
Branchnamen gut: <usernamer>_<feature>.
Das verstehe ich auch ganz bewusst nicht als "Finger weg!", sondern als 
"schau mal, hier ist Code, wenn Du Fragen hast, sprich die genannte 
Person an".

Der babel-branch ist älter als diese Erkenntnis, daher hat der das 
Schema noch nicht umgesetzt. Umbenennen ist aber nicht sinnvoll, solange 
der PR noch offen ist. Wir dünnen die Inhalte, die da drin sind 
sukzessive aus und dann fällt der weg. Ich baue auch keine neuen 
Features mehr darin, es geht nur noch um Mergebarkeit.

Im aktuellen Ansatz haben wir tendenziell auch sehr experimentelle 
Branches im git repository. Ich könnte mir vorstellen, dass wir aufhören 
in unserem git zu entwickeln und uns mehr an die best-practice halten, 
in eigenen persönlichen git-forks zu arbeiten und diese dann nach ffm zu 
upstreamen bevor diese nach gluon kommen. Das wird (nach auslaufen der 
bestehenden Branches) die Anzahl reduzieren. Das hieße, dass ich den 
dev-branch auf den Stand des n_babel-work-branches setzen würde und das 
wir dann von dort aus weiter laufen.

Nachteil wäre, dass Code-Beiträge erst später, wenn überhaupt, sichtbar 
werden.

Was meint ihr dazu?

viele Grüße

Christof

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by oszilloskop** [comment]
> Ich könnte mir vorstellen, dass wir aufhören
in unserem git zu entwickeln und uns mehr an die best-practice halten,
in eigenen persönlichen git-forks zu arbeiten und diese dann nach ffm zu
upstreamen bevor diese nach gluon kommen.

Da bin ich dafür 👍
