### ISSUE TITLE
Add kmod-rt2800-usb for RaspberryPi Targets

### ISSUE THREAD

**Issue by renne** [freifunk-ffm/site-ffffm#19]
A lot of WLAN-USB-Sticks recommended for RaspberryPi use RA-Link-chipsets.

kmod-rt2800-usb adds support for [Ralink RT2070, RT2770, RT2870, RT3070, RT3071, RT3072, RT3370, RT3572, RT5370, RT5372, RT5572 devices.](https://wiki.debian.org/rt2800usb)

[RT5572](https://www.amazon.de/gp/product/B00LLIOT34) supports 2.4 and 5 GHz 802.11a/b/g/n 2T2R-MIMO with 300MBi/s.

**Comment by oszilloskop** [comment]
We will also add `'kmod-rt2500-usb'` for Ralink RT2500USB/RT2571 devices.
