### ISSUE TITLE
Babel: Mesh-VPN default-mässig aktivieren.

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/site-ffffm#20]
In der Babel site.conf sollte Mesh-VPN per Default aktiviert sein. Dieses ist zur Zeit nicht der Fall.

```
   mesh_vpn = {
+    enabled = true,
     mtu = 1374,
```

**Comment by christf** [comment]
Stimmt. Wird geändert. 

Am 11. Dezember 2017 02:07:28 MEZ schrieb oszilloskop <notifications@github.com>:

**Comment by christf** [comment]
Done. 

Am 11. Dezember 2017 02:07:28 MEZ schrieb oszilloskop <notifications@github.com>:
