### ISSUE TITLE
test 2018-07-27

### ISSUE THREAD

**Issue by skorpy2009** [freifunk-ffm/site-ffffm#27]

**Comment by oszilloskop** [comment]
Was ist mit der Test 2018-07-27 ?
Gibt es die schon?

**Comment by skorpy2009** [comment]
Das ist ein test für die irc webhook

**Comment by skorpy2009** [comment]
test

**Comment by skorpy2009** [comment]
ein weiterer test

**Comment by oszilloskop** [comment]
Bei meinen inflationären Commits wünsche ich Euch dann viel Spass damit :o)

**Comment by skorpy2009** [comment]
hmmm
