### ISSUE TITLE
Site.conf der aktuellen Stable-Firmware

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/site-ffffm#34]
Es gibt eine Fehlkonfiguration in der site.conf der Stable.
Der opkg-Link zu den Kernel-spezifischen Modulen zeigt auf den Download-Bereich der Test-FW anstelle auf den Download-Bereich der Stable-FW.
Dadurch können Benutzer einer mit dieser site.conf gebauten Firmware keine Kernel-spezifischen Module nachladen.

Siehe Stable site.conf Zeile 120:
https://github.com/freifunk-ffm/site-ffffm/blob/stable/site.conf#L120

**Comment by skorpy2009** [comment]
Unpraktisch, wird dann mit dem 11s only Domain Build gefixt...?

**Comment by MyIgel** [comment]
Man könnte auch einfach den entsprechenden Ordner symlinken? Dann hat zwar die Test das Problem was allerdings mmn verkraftbar ist?

**Comment by skorpy2009** [comment]
Sounds fair

**Comment by oszilloskop** [comment]
Unschön, aber der Module-Verzeichnisname der Stable (dann in der Test) ist ja eineindeutig. Also hat danach keine Firmware ein Problem.

**Comment by oszilloskop** [comment]
> Unpraktisch, wird dann mit dem 11s only Domain Build gefixt...?

Ich empfehle dann auch in der site.conf der Stabel-FW die Zeilen [40](https://github.com/freifunk-ffm/site-ffffm/blob/stable/site.conf#L40) und [41](https://github.com/freifunk-ffm/site-ffffm/blob/stable/site.conf#L41) (disable von mesh_on_wan/mesh_on_lan) zu entfernen.
Einmal ist die Konfig dort total fehl am Platz, die zeitliche Wirkung ist mir nicht bekannt (nur Firstboot und/oder Sysupgrade) und habe ich nicht mehr wirklich eine Ahnung warum ich die damals aufgenommen habe. Sie ist da irgendwie aus der Test in die Stable gewandert. 
In der Dev und der Test ist das schön länger rausgeflogen.

Edit:
Da war irgendwas mit der Vermeidung von mesh-VPN- und MoW-Verwendung gleichzeitig angedacht. Das war aber ein Denkfehler.

**Comment by margau** [comment]
Fixed in #37
