### ISSUE TITLE
Auffälligkeiten der Stable-FW v3.2-stable-0903

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/site-ffffm#35]
- Auf der Map, im Konfigmodus und über den Befehl `'nodeinfo'` wird bei der Stable-FW v3.2 für die verwendetet Gluon-Version folgendes ausgegeben: `v3.1-stable-0711-23-ga08159ac`.
Diese Gluon-Version gibt es jedoch nicht.

- Die Befehle `'help'` und `'nodeinfo'` sind auf 11s ausgerichtet, nicht jedoch auf das temporär noch verwendetet IBSS. (Um Irritationen zu vermeiden, evtl. kleiner Hinweiss an die Routeraufsteller.)
Nach der Umschaltung auf 11s ist dieses Problem nicht mehr relevant.

**Comment by skorpy2009** [comment]
@oszilloskop stimme zweiterem zu, hättest du da eine Idee für?

**Comment by skorpy2009** [comment]
> Diese Gluon-Version gibt es jedoch nicht.

@margau weist du was da passiert ist?

**Comment by oszilloskop** [comment]
> hättest du da eine Idee für?

@skorpy2009 
Kurze Notiz an die ML und/oder den Block, dass bis zur Umstellung auf 11s im Text von `'help'` immer 'ibss' statt 'mesh' gemeint ist. Weiterhin die Info, dass bis zur Umstellung auf 11s das Tool `'nodeinfo'` fälschlicherweise keine Informationen zur Konfiguration von Wifi-Meshes  (enable/disable), sowie auch keine Schnellanalyse der Mesh-Qualität ausgibt.

**Comment by oszilloskop** [comment]
Gibt es Dokumentation zu der Stable v3.2 und wurden die Sourcen getaggt?

**Comment by margau** [comment]
Dokumentation existiert in Form eines Blog-Posts und der ML, Tags gibt es momentan nicht, könnte man nachholen.

**Comment by oszilloskop** [comment]
Naja, Blog-Eintrag und ML sagen nur, dass es die v3.2 gibt und sie irgendwas mit 11s zu tun hat.
Die Firmware-Historie mit Information zur verwendete Gluon-Version, neu unterstützte Hardware etc. sind da auch von Interesse. Speziell wenn es darum geht, ab wann wurde was bei uns eingesetzt. Hat uns schon einige male geholfen so eine Firmware-Historie.

**Comment by margau** [comment]
Fixed in #37
