### ISSUE TITLE
Zukünftig zu erwartende Belegung von Flash-Speicher bei 4/32-Geräten 

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/site-ffffm#43]
Auf Grund der Knappheit von Flash-Speicher bei 4/32-Geräten habe ich mal geschaut wie es sich mit den notwendig freien Erase-Blöcken (EB) in unserer ffffm-Firmware verhält bzw. zukünftig verhalten wird.  

- Mit der aktuellen Stable-Firmware sind 8 EB neben der Firmware vorhanden.
- Während der Umstellung von Batman14 auf Batman15 werden 7 EB zur Verfügung stehen.
- Nach der Umstellung werden mit Batman15 only wieder 8 EB vorhanden sein.

Die zu Grunde liegenden Berechnungen können hier in unserem Wiki eingesehen werden:
https://wiki.ffm.freifunk.net/firmware:jffs2-eb-buffer

Die Berechnungen zeigen auch, dass sich mit unterschiedlichsten Site-Konfigurationen keine Änderung des Ergebnisses einstellt. Dieses Erkenntnis sollte im PR #42 berücksichtigt werden.

**Comment by oszilloskop** [comment]
Die Tabelle der Flash-Nutzung auf https://wiki.ffm.freifunk.net/firmware:jffs2-eb-buffer wurde um aktuelle Firmware-Versionen erweitert.

**Comment by oszilloskop** [comment]
Die Tabelle der Flash-Nutzung auf https://wiki.ffm.freifunk.net/firmware:jffs2-eb-buffer wurde um aktuelle Firmware-Versionen erweitert.

**Comment by margau** [comment]
Ich denke, wir können das Issue im Hinblick auf https://openwrt.org/supported_devices/432_warning ("OpenWrt support for those devices will end with the 19.07 release") schließen.
