### ISSUE TITLE
Mit der Firmware v3.4-stable-1006 funktioniert "batctl ping" nicht

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/site-ffffm#45]
Die folgende Befehlsfolge funktioniert unter der Firmware v3.4-stable-1006 nicht mehr:

> GATEWAYMAC=$(batctl gwl | grep -e "^=>" -e "^\*" | awk -F'[ ]' '{print $2}')
> batctl ping -c 5 $GATEWAYMAC

Mit der v3.3.1-stable-2109 hat die obige Befehlsfolge noch funktioniert.

Dieses ist wichtig zu wissen, für z.B. Knotenaufsteller welche eigenerstellte Monitor-Skripte verwenden.

**Comment by margau** [comment]
Hallo,
das Problem liegt vermutlich beim Zusammenspiel aus der aktuellen Batctl-Version und Batman 14. Sollte also mit der Migration gefixt sein.

**Comment by oszilloskop** [comment]
Das wäre dann aber mal ein Hinweis an die Community wert.

**Comment by oszilloskop** [comment]
Mit der Firmware v4.1-test-0911 funktioniert die oben aufgeführte Befehlsfolge wieder.
