### ISSUE TITLE
Anpassung Autoupdate-URL

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/site-ffffm#7]
Wegen neuen DNS-Dingen sollte in der 'site.conf' die aktuelle Autoupdate-URL
von http://1.updates.services.ffffm/stable/sysupgrade
auf http://updates.services.ffffm/stable/sysupgrade
geändert werden.

**Comment by oszilloskop** [comment]
Done 59ddec1

**Comment by oszilloskop** [comment]
@skorpy2009 hätte gerne noch fast.updates.services.ffffm in die Liste der Updateserver aufgenommen.

**Comment by christf** [comment]
Warum brauchen wir das? Dafür ist DNS da.

Am 1. Juli 2016 23:54:35 MESZ, schrieb oszilloskop notifications@github.com:

> Reopened #7.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/freifunk-ffm/site-ffffm/issues/7#event-710990467

Viele Grüße

## Christof

Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by oszilloskop** [comment]
Da @skorpy2009 keine Argumente bringt -> Closed
